name: vibes
description: Micro-apps for human beings.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  bloc: ^9.0.0
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

assets:
  - assets/icon